name: goreleaser
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  goreleaser:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with: {go-version: '1.13.6'}
      - uses: goreleaser/goreleaser-action@v1
        with:
          version: v0.117.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
