name: test
on: [push]
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
        - uses: actions/checkout@v1
        - run: make lint
  e2e:
    runs-on: ubuntu-18.04
    needs:
      - lint
    steps:
      - uses: actions/checkout@v1
      - name: Run E2E tests
        run: |
          make test-e2e
